const errorResponse = (description: string): Record<string, unknown> => ({
  description,
  content: {
    'application/json': {
      schema: { $ref: '#/components/schemas/ErrorResponse' },
    },
  },
});

export const standardErrorResponses = {
  BadRequest: errorResponse('Некоректні параметри, query або тіло запиту'),
  Unauthorized: errorResponse('Автентифікація відсутня або недійсна'),
  Forbidden: errorResponse('Недостатньо дозволів для операції'),
  NotFound: errorResponse('Запитаний ресурс не знайдено'),
  Conflict: errorResponse('Операція конфліктує з поточним станом ресурсу'),
  UnprocessableEntity: errorResponse('Зовнішня служба відхилила коректно сформований запит'),
  InternalServerError: errorResponse('Внутрішня помилка сервера'),
  BadGateway: errorResponse('Зовнішня служба повернула неочікувану відповідь'),
  ServiceUnavailable: errorResponse('Зовнішня служба тимчасово недоступна'),
  GatewayTimeout: errorResponse('Зовнішня служба не відповіла в межах таймауту'),
} as const;

/** Monetary amounts travel as decimal strings, never as JSON numbers. */
const money = {
  type: 'string',
  pattern: '^\\d{1,12}(?:\\.\\d{1,2})?$',
  description: 'Десяткове число у вигляді рядка.',
} as const;

const currency = { type: 'string', pattern: '^[A-Z]{3}$' } as const;

export const openApiComponents = {
  securitySchemes: {
    bearerAuth: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
      description: 'Access token з відповіді login або refresh.',
    },
    refreshCookie: {
      type: 'apiKey',
      in: 'cookie',
      name: 'refresh_token',
      description: 'HttpOnly refresh cookie, яку сервер встановлює під час login або refresh.',
    },
  },
  responses: standardErrorResponses,
  parameters: {
    IdPath: {
      name: 'id',
      in: 'path',
      required: true,
      schema: { type: 'string', format: 'uuid' },
    },
    Page: {
      name: 'page',
      in: 'query',
      schema: { type: 'integer', minimum: 1, default: 1 },
    },
    PageSize20: {
      name: 'pageSize',
      in: 'query',
      schema: { type: 'integer', minimum: 1, maximum: 100, default: 20 },
    },
    PageSize25: {
      name: 'pageSize',
      in: 'query',
      schema: { type: 'integer', minimum: 1, maximum: 100, default: 25 },
    },
  },
  schemas: {
    ErrorResponse: {
      type: 'object',
      required: ['error', 'requestId'],
      properties: {
        error: {
          type: 'object',
          required: ['code', 'message'],
          properties: {
            code: { type: 'string', example: 'VALIDATION_ERROR' },
            message: { type: 'string', example: 'Request validation failed' },
            details: { nullable: true },
          },
        },
        requestId: { type: 'string' },
      },
    },
    Permission: {
      type: 'object',
      required: ['resource', 'action', 'scope'],
      properties: {
        resource: { type: 'string', pattern: '^[a-z][a-z0-9_-]*$', maxLength: 64 },
        action: { type: 'string', pattern: '^[a-z][a-z0-9_-]*$', maxLength: 64 },
        scope: { type: 'string', enum: ['ALL', 'OWN'] },
      },
    },
    AuthenticatedUser: {
      type: 'object',
      required: ['id', 'email', 'name', 'roles', 'permissions'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        email: { type: 'string', format: 'email' },
        name: { type: 'string' },
        roles: { type: 'array', items: { type: 'string' } },
        permissions: { type: 'array', items: { $ref: '#/components/schemas/Permission' } },
      },
    },
    AuthPayload: {
      type: 'object',
      required: ['user', 'accessToken', 'accessTokenExpiresInSeconds'],
      properties: {
        user: { $ref: '#/components/schemas/AuthenticatedUser' },
        accessToken: { type: 'string' },
        accessTokenExpiresInSeconds: { type: 'integer', minimum: 1, example: 900 },
      },
    },
    RoleSummary: {
      type: 'object',
      required: ['id', 'name'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        name: { type: 'string' },
      },
    },
    User: {
      type: 'object',
      required: ['id', 'email', 'name', 'isActive', 'roles', 'createdAt', 'updatedAt'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        email: { type: 'string', format: 'email' },
        name: { type: 'string' },
        isActive: { type: 'boolean' },
        roles: { type: 'array', items: { $ref: '#/components/schemas/RoleSummary' } },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    UserSession: {
      type: 'object',
      required: [
        'id',
        'userId',
        'expiresAt',
        'revokedAt',
        'ipAddress',
        'userAgent',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        userId: { type: 'string', format: 'uuid' },
        expiresAt: { type: 'string', format: 'date-time' },
        revokedAt: { type: 'string', format: 'date-time', nullable: true },
        ipAddress: { type: 'string', nullable: true },
        userAgent: { type: 'string', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    Role: {
      type: 'object',
      required: ['id', 'name', 'description', 'permissions', 'createdAt', 'updatedAt'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        name: { type: 'string' },
        description: { type: 'string', nullable: true },
        permissions: { type: 'array', items: { $ref: '#/components/schemas/Permission' } },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    Contact: {
      type: 'object',
      required: [
        'id',
        'ownerId',
        'firstName',
        'lastName',
        'email',
        'phone',
        'company',
        'notes',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        ownerId: { type: 'string', format: 'uuid' },
        firstName: { type: 'string' },
        lastName: { type: 'string' },
        email: { type: 'string', format: 'email', nullable: true },
        phone: { type: 'string', nullable: true },
        company: { type: 'string', nullable: true },
        notes: { type: 'string', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    Deal: {
      type: 'object',
      required: [
        'id',
        'ownerId',
        'contactId',
        'title',
        'stage',
        'amount',
        'currency',
        'probability',
        'version',
        'expectedCloseDate',
        'closedAt',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        ownerId: { type: 'string', format: 'uuid' },
        contactId: { type: 'string', format: 'uuid', nullable: true },
        title: { type: 'string' },
        stage: { $ref: '#/components/schemas/DealStage' },
        amount: { type: 'string', pattern: '^\\d{1,12}(?:\\.\\d{1,2})?$' },
        currency: { type: 'string', pattern: '^[A-Z]{3}$' },
        probability: { type: 'integer', minimum: 0, maximum: 100 },
        version: { type: 'integer', minimum: 1 },
        expectedCloseDate: { type: 'string', format: 'date-time', nullable: true },
        closedAt: { type: 'string', format: 'date-time', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    DealStage: {
      type: 'string',
      enum: ['LEAD', 'QUALIFIED', 'PROPOSAL', 'WON', 'LOST'],
    },
    AuditRecord: {
      type: 'object',
      required: [
        'id',
        'actorId',
        'action',
        'entityType',
        'entityId',
        'changes',
        'metadata',
        'ipAddress',
        'createdAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        actorId: { type: 'string', format: 'uuid', nullable: true },
        action: { type: 'string' },
        entityType: { type: 'string' },
        entityId: { type: 'string', format: 'uuid', nullable: true },
        changes: { type: 'object', additionalProperties: true, nullable: true },
        metadata: { type: 'object', additionalProperties: true, nullable: true },
        ipAddress: { type: 'string', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
    Product: {
      type: 'object',
      required: [
        'id',
        'sku',
        'name',
        'description',
        'category',
        'unitPrice',
        'currency',
        'isActive',
        'version',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        sku: { type: 'string', maxLength: 64, description: 'Незмінний після створення.' },
        name: { type: 'string' },
        description: { type: 'string', nullable: true },
        category: { type: 'string', nullable: true },
        unitPrice: money,
        currency,
        isActive: { type: 'boolean' },
        version: { type: 'integer', minimum: 1 },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    OrderStatus: {
      type: 'string',
      enum: ['DRAFT', 'CONFIRMED', 'PAID', 'FULFILLED', 'CANCELLED'],
    },
    OrderItem: {
      type: 'object',
      required: [
        'id',
        'orderId',
        'productId',
        'sku',
        'name',
        'quantity',
        'unitPrice',
        'lineTotal',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        orderId: { type: 'string', format: 'uuid' },
        productId: { type: 'string', format: 'uuid' },
        sku: { type: 'string', description: 'Знімок каталогу на момент додавання рядка.' },
        name: { type: 'string' },
        quantity: { type: 'integer', minimum: 1 },
        unitPrice: money,
        lineTotal: money,
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    Order: {
      type: 'object',
      required: [
        'id',
        'orderNumber',
        'ownerId',
        'contactId',
        'dealId',
        'status',
        'currency',
        'subtotal',
        'discountTotal',
        'taxTotal',
        'total',
        'notes',
        'version',
        'placedAt',
        'createdAt',
        'updatedAt',
        'items',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        orderNumber: { type: 'string', description: 'Видається сервером.' },
        ownerId: { type: 'string', format: 'uuid' },
        contactId: { type: 'string', format: 'uuid', nullable: true },
        dealId: { type: 'string', format: 'uuid', nullable: true },
        status: { $ref: '#/components/schemas/OrderStatus' },
        currency,
        subtotal: money,
        discountTotal: money,
        taxTotal: money,
        total: { ...money, description: 'Обчислюється сервером із рядків замовлення.' },
        notes: { type: 'string', nullable: true },
        version: { type: 'integer', minimum: 1 },
        placedAt: { type: 'string', format: 'date-time', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
        items: { type: 'array', items: { $ref: '#/components/schemas/OrderItem' } },
      },
    },
    Warehouse: {
      type: 'object',
      required: ['id', 'code', 'name', 'isActive', 'createdAt', 'updatedAt'],
      properties: {
        id: { type: 'string', format: 'uuid' },
        code: { type: 'string', maxLength: 32, description: 'Незмінний після створення.' },
        name: { type: 'string' },
        isActive: { type: 'boolean' },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    StockLevel: {
      type: 'object',
      required: [
        'id',
        'warehouseId',
        'productId',
        'quantityOnHand',
        'quantityReserved',
        'quantityAvailable',
        'version',
        'createdAt',
        'updatedAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        warehouseId: { type: 'string', format: 'uuid' },
        productId: { type: 'string', format: 'uuid' },
        quantityOnHand: { type: 'integer', minimum: 0 },
        quantityReserved: { type: 'integer', minimum: 0 },
        quantityAvailable: {
          type: 'integer',
          minimum: 0,
          description: 'Похідне значення: quantityOnHand − quantityReserved.',
        },
        version: { type: 'integer', minimum: 1 },
        createdAt: { type: 'string', format: 'date-time' },
        updatedAt: { type: 'string', format: 'date-time' },
      },
    },
    StockMovementType: {
      type: 'string',
      enum: ['RECEIPT', 'ISSUE', 'RESERVATION', 'RELEASE', 'ADJUSTMENT'],
    },
    StockMovement: {
      type: 'object',
      required: [
        'id',
        'warehouseId',
        'productId',
        'type',
        'quantity',
        'referenceType',
        'referenceId',
        'actorId',
        'note',
        'createdAt',
      ],
      properties: {
        id: { type: 'string', format: 'uuid' },
        warehouseId: { type: 'string', format: 'uuid' },
        productId: { type: 'string', format: 'uuid' },
        type: { $ref: '#/components/schemas/StockMovementType' },
        quantity: { type: 'integer' },
        referenceType: { type: 'string', nullable: true },
        referenceId: { type: 'string', format: 'uuid', nullable: true },
        actorId: { type: 'string', format: 'uuid', nullable: true },
        note: { type: 'string', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
    SettingKey: {
      type: 'string',
      enum: [
        'organization.defaultCurrency',
        'organization.name',
        'orders.numberPrefix',
        'warehouse.defaultCode',
      ],
    },
    Setting: {
      type: 'object',
      required: ['key', 'value', 'description', 'updatedById', 'updatedAt', 'source'],
      properties: {
        key: { $ref: '#/components/schemas/SettingKey' },
        value: {
          description: 'Тип значення визначає реєстр налаштувань для конкретного ключа.',
        },
        description: { type: 'string' },
        updatedById: { type: 'string', format: 'uuid', nullable: true },
        updatedAt: { type: 'string', format: 'date-time', nullable: true },
        source: {
          type: 'string',
          enum: ['database', 'default'],
          description: '`default` означає, що рядка ще немає і віддано значення з реєстру.',
        },
      },
    },
    SalesSummaryReport: {
      type: 'object',
      required: ['from', 'to', 'period', 'totals', 'series'],
      properties: {
        from: { type: 'string', format: 'date-time' },
        to: { type: 'string', format: 'date-time' },
        period: { type: 'string', enum: ['day', 'week', 'month'] },
        totals: {
          type: 'object',
          required: ['orderCount', 'revenue', 'averageOrderValue'],
          properties: {
            orderCount: { type: 'integer', minimum: 0 },
            revenue: money,
            averageOrderValue: money,
          },
        },
        series: {
          type: 'array',
          items: {
            type: 'object',
            required: ['bucketStart', 'orderCount', 'revenue'],
            properties: {
              bucketStart: { type: 'string', format: 'date-time' },
              orderCount: { type: 'integer', minimum: 0 },
              revenue: money,
            },
          },
        },
      },
    },
    DealFunnelReport: {
      type: 'object',
      required: ['from', 'to', 'stages', 'conversions'],
      properties: {
        from: { type: 'string', format: 'date-time' },
        to: { type: 'string', format: 'date-time' },
        stages: {
          type: 'array',
          items: {
            type: 'object',
            required: ['stage', 'count', 'amount'],
            properties: {
              stage: { $ref: '#/components/schemas/DealStage' },
              count: { type: 'integer', minimum: 0 },
              amount: money,
            },
          },
        },
        conversions: {
          type: 'array',
          items: {
            type: 'object',
            required: ['from', 'to', 'rate'],
            properties: {
              from: { $ref: '#/components/schemas/DealStage' },
              to: { $ref: '#/components/schemas/DealStage' },
              rate: {
                type: 'number',
                minimum: 0,
                maximum: 1,
                description: 'Частка в діапазоні [0, 1], округлена до чотирьох знаків.',
              },
            },
          },
        },
      },
    },
    TopProductsReport: {
      type: 'object',
      required: ['from', 'to', 'limit', 'items'],
      properties: {
        from: { type: 'string', format: 'date-time' },
        to: { type: 'string', format: 'date-time' },
        limit: { type: 'integer', minimum: 1 },
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: ['productId', 'sku', 'name', 'quantity', 'revenue'],
            properties: {
              productId: { type: 'string', format: 'uuid' },
              sku: { type: 'string' },
              name: { type: 'string' },
              quantity: { type: 'integer', minimum: 0 },
              revenue: money,
            },
          },
        },
      },
    },
    OwnerPerformanceReport: {
      type: 'object',
      required: ['from', 'to', 'items'],
      properties: {
        from: { type: 'string', format: 'date-time' },
        to: { type: 'string', format: 'date-time' },
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'ownerId',
              'name',
              'email',
              'dealCount',
              'dealAmount',
              'wonDealCount',
              'wonDealAmount',
              'winRate',
              'orderCount',
              'orderRevenue',
            ],
            properties: {
              ownerId: { type: 'string', format: 'uuid' },
              name: { type: 'string', nullable: true },
              email: { type: 'string', format: 'email', nullable: true },
              dealCount: { type: 'integer', minimum: 0 },
              dealAmount: money,
              wonDealCount: { type: 'integer', minimum: 0 },
              wonDealAmount: money,
              winRate: { type: 'number', minimum: 0, maximum: 1 },
              orderCount: { type: 'integer', minimum: 0 },
              orderRevenue: money,
            },
          },
        },
      },
    },
    StockHealthReport: {
      type: 'object',
      required: ['threshold', 'limit', 'items'],
      properties: {
        threshold: { type: 'integer', minimum: 0 },
        limit: { type: 'integer', minimum: 1 },
        items: {
          type: 'array',
          items: {
            type: 'object',
            required: [
              'productId',
              'sku',
              'name',
              'warehouseId',
              'warehouseCode',
              'quantityOnHand',
              'quantityReserved',
              'quantityAvailable',
            ],
            properties: {
              productId: { type: 'string', format: 'uuid' },
              sku: { type: 'string' },
              name: { type: 'string' },
              warehouseId: { type: 'string', format: 'uuid' },
              warehouseCode: { type: 'string' },
              quantityOnHand: { type: 'integer' },
              quantityReserved: { type: 'integer' },
              quantityAvailable: { type: 'integer' },
            },
          },
        },
      },
    },
    DeliveryAddress: {
      type: 'object',
      required: ['country', 'city', 'postalCode', 'line1'],
      properties: {
        country: {
          type: 'string',
          pattern: '^[A-Za-z]{2}$',
          description: 'Код країни ISO 3166-1 alpha-2.',
        },
        city: { type: 'string', minLength: 1, maxLength: 120 },
        postalCode: { type: 'string', minLength: 1, maxLength: 20 },
        line1: { type: 'string', minLength: 1, maxLength: 200 },
      },
    },
    DeliveryParcel: {
      type: 'object',
      required: ['weightGrams', 'lengthCm', 'widthCm', 'heightCm'],
      properties: {
        weightGrams: { type: 'integer', minimum: 1, maximum: 1000000 },
        lengthCm: { type: 'integer', minimum: 1, maximum: 500 },
        widthCm: { type: 'integer', minimum: 1, maximum: 500 },
        heightCm: { type: 'integer', minimum: 1, maximum: 500 },
      },
    },
    DeliveryQuote: {
      type: 'object',
      required: [
        'quoteId',
        'carrier',
        'service',
        'amount',
        'currency',
        'estimatedDays',
        'expiresAt',
      ],
      properties: {
        quoteId: { type: 'string' },
        carrier: { type: 'string' },
        service: { type: 'string' },
        amount: money,
        currency,
        estimatedDays: { type: 'integer', minimum: 0 },
        expiresAt: { type: 'string', format: 'date-time' },
      },
    },
    ShipmentStatus: {
      type: 'string',
      enum: ['CREATED', 'IN_TRANSIT', 'DELIVERED', 'CANCELLED', 'FAILED'],
    },
    Shipment: {
      type: 'object',
      required: [
        'shipmentId',
        'orderId',
        'status',
        'carrier',
        'trackingNumber',
        'createdAt',
        'estimatedDeliveryAt',
      ],
      properties: {
        shipmentId: { type: 'string' },
        orderId: { type: 'string' },
        status: { $ref: '#/components/schemas/ShipmentStatus' },
        carrier: { type: 'string' },
        trackingNumber: { type: 'string', nullable: true },
        createdAt: { type: 'string', format: 'date-time' },
        estimatedDeliveryAt: { type: 'string', format: 'date-time', nullable: true },
      },
    },
    DeliveryHealth: {
      type: 'object',
      required: ['transport', 'circuitState', 'consecutiveFailures', 'lastErrorAt', 'openedAt'],
      properties: {
        transport: { type: 'string', enum: ['stub', 'http'] },
        circuitState: { type: 'string', enum: ['closed', 'open', 'half-open'] },
        consecutiveFailures: { type: 'integer', minimum: 0 },
        lastErrorAt: { type: 'string', format: 'date-time', nullable: true },
        openedAt: { type: 'string', format: 'date-time', nullable: true },
      },
    },
    AiDealSummary: {
      type: 'object',
      required: ['dealId', 'summary', 'provider', 'cached'],
      properties: {
        dealId: { type: 'string', format: 'uuid' },
        summary: { type: 'string' },
        provider: { type: 'string', description: 'Ідентифікатор провайдера, напр. `mock`.' },
        cached: { type: 'boolean', description: 'Відповідь віддано з кешу.' },
      },
    },
    AiInquiryClassification: {
      type: 'object',
      required: ['category', 'confidence', 'provider', 'cached'],
      properties: {
        category: {
          type: 'string',
          enum: [
            'billing',
            'sales',
            'technical_support',
            'shipping',
            'complaint',
            'other',
            'unknown',
          ],
          description: '`unknown` — модель повернула значення поза закритим списком.',
        },
        confidence: { type: 'number', minimum: 0, maximum: 1 },
        provider: { type: 'string' },
        cached: { type: 'boolean' },
      },
    },
  },
} as const;
